### PR TITLE
OSX Sign and notarise

### PR DESCRIPTION
**Pull request by e9gille**
Change the way we sign and notarise RIDE.

### CODE REVIEW

**Review by dyaandys — COMMENTED** [review]
Hi Gil .. you have a typo on line 27

echo $resuest_info

**Comment by JasonRivers** [comment]
Sorry @e9gille , Are you able to merge package.json / package-lock.json in to this branch, and then I can approve the PR - I missed that it was here unfortunately!

**Comment by e9gille** [comment]
I'll update the branch, but make sure you can use the new tool on the build server (I've replace `altool` with `notarytool`) before merging in.

**Review by JasonRivers — APPROVED** [review]
Hi @e9gille I have updated the Jenkinsfile to force macOS builds to use a Mac that has notarytool installed, This should be good to merge now.

#954 should be resolved once merged in.

**Pull request merged**
